workflows:
  ios-release:
    name: iOS Release (auto-sign)

    integrations:
      app_store_connect: codemagic-key   # UI’de eklediğiniz API anahtarının "key" alanı

    environment:
      flutter: stable
      xcode: 16.4
      groups:
        - ios

    scripts:
      - name: Build IPA
        script: flutter build ipa --release

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

