workflows:
  ios-release:
    name: iOS Release (auto-sign)

    integrations:
      app_store_connect: codemagic-key   # UI’de eklediğiniz API anahtarının "key" alanı

    environment:
      flutter: stable
      xcode: 16.4

    scripts:
      - name: Build IPA
        script: flutter build ipa --release

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:    $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true

