workflows:
  ios-release:
    name: iOS Release (auto-sign)

    integrations:
      app_store_connect: codemagic-key   # UI’de eklediğiniz API anahtarının "key" alanı

    environment:
      flutter: stable
      xcode: 16.4
      groups:
        - ios

    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id com.yalpertem.havahizli
          keychain add-certificates    
      - name: Build IPA
        script: flutter build ipa --release

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

